### ISSUE TITLE
View command not showing model preview

### ISSUE THREAD

**Issue by sebastianewak** [Activision/USDShellExtension#3]
Hi, my colleague, a 3D artist, asked me to build this awesome tool for him.

I've managed to get all the way through, so the extension and the installer build without errors, the extension is properly installed and new commands are available for USD, however, when I choose the view option, nothing happens.

There's no error, I don't see anything in the Event Log. The usdview works correctly when invoked directly from the command line. Other extension actions like crate seem to work, as new files are being generated as a result.

I'm using Python 3.6 with USD built using build_usd.py with the parameters described in the docs.

I'd appreciate any tips as to what I might be doing wrong. Thanks!

**Comment by pmintus** [comment]
The shell extension may not be able to locate python.

These features require python, the rest just use C++.
- View
- Windows Explorer Preview
- Windows Explorer Thumbnails

If you know the root folder of your python install, open the UsdShellExtension.ini file (there is a shortcut in the start menu).

If the root folder for your python install is C:\Python36 then set the Python section of the ini file to these values:

```
[PYTHON]
PATH=C:\Python36\
PYTHONPATH=C:\Python36\Lib\;C:\Python36\DLLs\
```

The docs describe building both a full USD build and a bare-bones monolithic USD build. The bare bones version will not have any python functionality, so make sure that you are pointing the shell extension in the ini file to the full build.

**Comment by sebastianewak** [comment]
Thank you for the quick response! I've updated both inis (all users and current users) to point to my Python 3.6 installation. I've also tried to set the paths to full USDB build. Unfortunately, the view command still doesn't open the model viewer.

**Comment by pmintus** [comment]
I don't have any more ideas off the top of my head. 

I would try downloading the pre-built NVIDIA USD binaries and pointing the shell extension to those. If that works then we've narrowed down the issue to the USD build.

**Comment by sebastianewak** [comment]
I spoke to my colleague again and what he really needed was just an USD viewer on Windows, so I showed him how to run the viewer from the command line and he was happy with it. I'm closing the issue as most likely it was my local setup and it doesn't make sense to spend time on it since the main problem is solved. Thank you for your assistance @pmintus!
