### ISSUE TITLE
Browser shell?

### ISSUE THREAD

**Issue by jeffscottward** [Activision/USDShellExtension#4]
Is there any way to preview a USD file inside a browser?

Could this be forked to do that? 

Or would you need WASM compiled version of USDView?

Im trying to make GLTF and USD work side by side in browser seamlessly. 

File type wars significantly degrade user experience and I am looking for a solution.

**Comment by jeffscottward** [comment]
Any updates on this?

**Comment by melMass** [comment]
Not sure what you mean by browser shell, but compiling USD for the Web (WASM) has been started by multiple teams/projects 
https://github.com/PixarAnimationStudios/USD/issues/1492
https://github.com/autodesk-forks/USD

**Comment by melMass** [comment]
I just got a notification since this was closed, today I would suggest the needle fork: https://github.com/needle-tools/usd-viewer
