### ISSUE TITLE
printTiming Error

### ISSUE THREAD

**Issue by thomasjaggard** [Activision/USDShellExtension#5]
Basically the Preview pane never loads. It shows the USD logo and the loading dots but never gets to a viewport.

Looked in event viewer, and I'm getting the following error when selecting any type of .usd file.

![image](https://user-images.githubusercontent.com/82520270/222477138-4c0a0edf-178b-4281-9c03-da60d95cf43a.png)

I've also noticed that the thumbnails only generate a preview after I've double clicked on the file to open.

This is running in Win10 with a fresh install of Python 3.7, Pyside2 and PyOpenGL. Pixar's USD tools work fine on their own.

**Comment by oumad** [comment]
Do you get the issue only for the preview pane ? what about when you double click a .usd file? does the usdview shows up fine ?

**Comment by thomasjaggard** [comment]
Hi apologies for the delay in replying, been out of office.

Yes only in the preview pane. When I double click the .usd files they open and I can view the models as expected

**Comment by thomasjaggard** [comment]
Anyone able to help with this? 
This issue has been reproduced on several machines, all exactly the same error and behaviour.

**Comment by oumad** [comment]
Apologies for not responding to your last message. Something took my attention right after seeing it.
All I can suspect is some version mismatch with python, in my case I installed the python 3.7 version (`UsdShellExtension-v1.09-u21.02-p3.7-setup.exe`), in my machine I have `python-3.7.9-amd64.exe` installed (it won't work with 3.6 for example), and of course that is the verison I compiled USD with (USD that is used for PATH, and PYTHONPATH). Make sure you have no other USD in your PATH or PYTHONPATH variables in your system or user environment that can cause conflict too.

**Comment by thomasjaggard** [comment]
Thanks Mohammed, I found what the issue was. I was using a pre-build of USD from Nvidia but I had version mismatched with the Shell Extension. It requires USD version 21.02, I was using 22.11. After downgrading that, everything works. Thanks anyway!

**Comment by oumad** [comment]
> Thanks Mohammed, I found what the issue was. I was using a pre-build of USD from Nvidia but I had version mismatched with the Shell Extension. It requires USD version 21.02, I was using 22.11. After downgrading that, everything works. Thanks anyway!

I'm confirming your find, I just tested on 22.11 version of USD that I built myself, and it does output the same error

![image](https://user-images.githubusercontent.com/17836943/227143793-55e6169f-0626-461f-bd9a-9590d07cbb67.png)

But when I try with v22.08 (that I also had built in the past), it works fine : 
![image](https://user-images.githubusercontent.com/17836943/227145630-69e7a8b1-951f-47dc-a388-a306a9cc11ad.png)


Something between v22.08 and 22.11 broke compatibility

**Comment by thomasjaggard** [comment]
Appreciate the test Mohammed, definitely good to know. Might roll out v22.08 instead. Many thanks.
